# name: lambda-deployment

# on: 
#   schedule:
#   - cron:  '30 7,12 * * *'
# defaults:
#   run:
#     working-directory: ./back-end/src
# jobs:
#   lambda-deploy:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/dev'
#     steps:
#       - name: Checkout to repo
#         uses: actions/checkout@v2

#       - name: Setup node environment
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'
          
#       - name: Install serverless globally
#         run: npm install -g serverless
      
#       - name: Configure serverless authentication
#         run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#       - name: Install npm dependencies
#         run: npm ci
     
#       - name: Deploy lambda function
#         run: sls deploy